# version: '3.9'
# services:
  # zookeeper:
  #   image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
  #   container_name: zookeeper_container
  #   ports:
  #     - 2181:2181
  #     - 2888:2888
  #     - 3888:3888
  # kafka:
  #   image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
  #   container_name: kafka
  #   ports:
  #     - 9092:9092
  #   links:
  #     - zookeeper
  #   environment:
  #     - ZOOKEEPER_CONNECT=zookeeper:2181

  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka_ui_container
  #   ports:
  #     - 9089:8080
  #   links:
  #     - kafka
  #   environment:
  #     - KAFKA_CLUSTERS_0_NAME=local
  #     - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
  # mysql:
  #   image: quay.io/debezium/example-mysql:${DEBEZIUM_VERSION}
  #   container_name: mysql_container
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Thanh2024
  #     MYSQL_USER: devuser
  #     MYSQL_PASSWORD: Thanh2024
  #   ports:
  #     - "3306:3306"
