version: '3.9'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Thanh2024
      MYSQL_DATABASE: shopdevgo
      MYSQL_USER: devuser
      MYSQL_PASSWORD: Thanh2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
  crm.shopdev.com:
    container_name: crm.shopdev.com
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8008:8002"

volumes:
  mysql_data:
  redis_data:
