server:
  port: 8082
  mode: "dev"
mysql:
  host: 127.0.0.1 # mysql_container
  port: 3306
  username: root
  password: Thanh2024
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  logLevel: debug
  filename: "./logs/dev.001.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 30
  compress: true
redis:
  host: 127.0.0.1 # redis_container
  port: 6381 # 6379
  password:
  database: 0
