server:
  port: 8082
  mode: "dev"
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: Thanh2024
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  logLevel: debug
  filename: "./logs/dev.001.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 30
  compress: true
redis:
  host: 127.0.0.1
  port: 6381
  password:
  database: 0
  # poolSize: 100
  # minIdleConns: 200
  # maxIdleConns: 400
  # connTimeout: 10
  # readTimeout: 10
  # writeTimeout: 10
  # dialTimeout: 10
  # poolTimeout: 10
  # idleTimeout: 10
  # maxConnAge: 10
  # connMaxLifetime: 10